name: Go CI/CD 

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Spécifiez la version de Go que vous utilisez

      - name: Build the Go executable
        run: go build -o cowsay main.go

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cowsay .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cowsay
